file(GLOB_RECURSE SRC_FILES  ${PROJECT_PATH}/*.c)

if (NOT USE_HAL)
    list(FILTER SRC_FILES EXCLUDE REGEX ".*/(.*(build|STM32-base).*)/.*")
else ()
    list(FILTER SRC_FILES EXCLUDE REGEX ".*/(.*(build).*)|STM32-base/.*")
    set(EXCLUDED_FILES
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_utils.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_usb.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_usart.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_tim.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_spi.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_sdmmc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_rtc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_rng.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_rcc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_pwr.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_lptim.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_i2c.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_gpio.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_fsmc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_fmpi2c.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_fmc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_exti.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_dma2d.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_dma.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_dac.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_crc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_ll_adc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_wwdg.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_usart.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_uart.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_tim_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_tim.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_sram.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_spi.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_spdifrx.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_smbus.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_smartcard.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_sdram.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_sd.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_sai_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_sai.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_rtc_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_rtc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_rng.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_rcc_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_qspi.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_pwr_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_pcd_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_pcd.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_pccard.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_nor.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_nand.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_mmc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_ltdc_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_ltdc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_lptim.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_irda.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_i2s_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_i2s.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_i2c_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_i2c.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_hcd.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_hash_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_hash.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_fmpsmbus.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_fmpi2c_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_fmpi2c.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_exti.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_eth.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dsi.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dma_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dma2d.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dma.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dfsdm.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dcmi_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dcmi.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dac_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_dac.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_cryp_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_cryp.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_crc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_cec.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_can.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_adc_ex.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_adc.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_timebase_tim_template.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_timebase_rtc_wakeup_template.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_timebase_rtc_alarm_template.c"
            "${PROJECT_PATH}/STM32-base-STM32Cube/HAL/${SERIES_FOLDER}/src/stm32f4xx_hal_msp_template.c"
    )
    list(REMOVE_ITEM SRC_FILES ${EXCLUDED_FILES})
endif ()

set(SOURCE_LIST ${SOURCE_LIST} ${SRC_FILES}
        ${PROJECT_PATH}/STM32-base-STM32Cube/CMSIS/${SERIES_FOLDER}/src/system_${SERIES_FOLDER}.c)